on:
  push:
    branches:
      - main  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-env-injection:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: In order to use the Pulumi v2 action, we need to setup the Pulumi project specific language environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Authenticate with Pulumi Cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: initech
          requested-token-type: urn:pulumi:token-type:access_token:organization
      - name: Install and inject ESC environment variables
        uses: pulumi/esc-action@v1
        with:
          environment: 'initech/shared/azure-dev'
      - name: Verify environment variables
        run: |
          echo "ARM_OIDC_TOKEN=$ARM_OIDC_TOKEN"
      - name: Install dependencies
        run: npm install    
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: initech/azure-serverless/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}