name: Pulumi
on:
  - pull_request

permissions:
  id-token: write
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set-up Node 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Authenticate with Pulumi Cloud
        uses: pulumi/auth-actions@v1
        with:
          organization: initech
          requested-token-type: urn:pulumi:token-type:access_token:organization

      - name: Install and inject ESC environment variables
        uses: pulumi/esc-action@v1
        with:
          environment: 'initech/shared/azure-dev'

      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: initech/azure-serverless/dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          upsert: true